SPNS:
  mz_min: 50.0
  mz_max: 500.0
  bin_size: 0.01
  start_rt: 3.70
  end_rt: 19.20
  rt_scan: 0.01
  label_mapping:
    Control: 0
    SPNS: 1
RCC:
  mz_min: 70.0
  mz_max: 1060.0
  bin_size: 0.1
  start_rt: 0.00
  end_rt: 10.00
  rt_scan: 0.01
  label_mapping:
    Control: 0
    RCC: 1
CD:
  mz_min: 65.0
  mz_max: 1010.0
  bin_size: 0.01
  start_rt: 0.00
  end_rt: 27.00
  rt_scan: 0.01
  label_mapping:
    Control: 0
    CD: 1