# Patch Strategy
GP:  # Grid Patching
  patch_height: 224
  patch_width: 224
  overlap_row: 0
  overlap_col: 0
DAPS:  # Density-Aware Peaks Selection
  patch_height: 224
  patch_width: 224
  min_peaks_in_patch: 5
  padding_value: 0.0