# Patch Strategy
GP:  # Grid Patching
  patch_height: 224
  patch_width: 224
  overlap_row: 0
  overlap_col: 0
DAPS:  # Density-Aware Peaks Selection
  patch_height: 224
  patch_width: 224
  window_size: 100
  intensity_percentile: 10
  density_percentile: 90
  min_peaks_in_patch: 10
  padding_value: 0.0